apiVersion: accelerator.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: "acc-name"
spec:
  tags:
    - "new-accelerator"
  git:
    url: "acc-git-url"
    ref:
      # use branch, tag, semver, or commit
      # see https://fluxcd.io/docs/components/source/gitrepositories/
      branch: "acc-git-branch"